at: mc: remove mutex lock in interrupt handler and modify ioexp init
facebook/OpenBIC pull request #1016
Opened 2023-03-31 07:57 UTC by KaidanWu-wiwynn

Summary
- If the interrupt handler can not lock the mutex, the handler will return false.
- Therefore,BIC will not set the PERST for cxl.
- Remove mutex lock for interrupt to prevent cpu context switch and return error without control.
- BIC should set output value of ioexp before modify the gpio direction of the ioexp.

Test Plan:
- Build code : pass
- AC and DC cycle that OS have all of the cxl pcie link.
- Checking the AC cycle waveform.

2023-03-31 08:23 UTC, KaidanWu-wiwynn commented
yv35-cl build Pass in our local build after patch Zephyr.
Dependency: [PR1015](https://github.com/facebook/OpenBIC/pull/1015)

2023-04-03 18:46 UTC, amithash commented
@KaidanWu-wiwynn This PR does not seem to be base on main and I cannot import it. It seems to have a bunch of changes from another PR.

2023-04-03 20:50 UTC, amithash requested changes
Please resolve conflicts and resend.

2023-04-10 01:58 UTC, KaidanWu-wiwynn commented
Hi @amithash,
We've resent it, please re-check again.
Thank you.

2023-04-13 03:24 UTC, closed without merging