Common: Fix util_worker time print issue
facebook/OpenBIC pull request #1025
Opened 2023-04-06 02:14 UTC by Yi-Shum

Summary:
- Change the get time function to 32 bits, because the LOG function not support print 64 bit argument.

Test Plan:
- Build code: PASS

Log:
```
before:
[00:00:07.217,000] <err> util_worker: WARN: work  Processing time too long, 359630496596968 ms
after:
[00:00:07.217,000] <err> util_worker: WARN: work  Processing time too long, 2004 ms
```

2023-04-06 22:57 UTC, zhdaniel12 requested changes
if it is just print out issue, why not handle this in print time?
BTW you are checking the duration, the high order bits will suppose to be 0.
4G ms = 4000s , I don't think we will have work duration is longer than 4000s, if so there must be something wrong. 
if do, a quick solution is print hex, or print estimated xxxxx.yy s, instead of ms
or create a utility function itoa_64.

2023-04-07 03:26 UTC, Yi-Shum commented
Hi Dan,
Thanks for the comment.

Zephyr Log API has issue when print 64 bits argument.
Do you mean it is better to directly convert 64bit to 32bit? Instead of using the k_uptime_get_32().

BTW, k_uptime_get32() returns the running time(ms) since BIC boot. So it will back to 0 after BIC runs 4Gms and we need to handle the overflow.
And I also think the work duration should not run too long, so print millisecond is good enough and also readable.

2023-04-10 18:22 UTC, zhdaniel12 commented
> Hi Dan, Thanks for the comment.
> 
> Zephyr Log API has issue when print 64 bits argument. Do you mean it is better to directly convert 64bit to 32bit? Instead of using the k_uptime_get_32().
> 
> BTW, k_uptime_get32() returns the running time(ms) since BIC boot. So it will back to 0 after BIC runs 4Gms and we need to handle the overflow. And I also think the work duration should not run too long, so print millisecond is good enough and also readable.

I am saying you shall keep on using k_uptime 64bit value, but the you are trying to print the task running duration, the duration is not expected to be longer than 4Gms that is 45 days. so you can convert the 64bit value to 32bit. 
BTW, if we do have task duration longer than 45days, your solution won't work either. So why not just keep on using 64bit absolute time and convert the duration value to 32 bit. If you do want to better cover 45D+ cases, you can check 
if (dur >> 32) { print("45 Days and %d second", (uint32_t)( dur >> 42 )") };

2023-04-11 11:12 UTC, Yi-Shum commented
Hi Daniel,
Thanks for your comment.
I force update the PR, please help to review again.
Thanks.

2023-04-12 18:25 UTC, closed without merging