common: ipmb: optimize ipmb mqueue get/set mechanism
facebook/OpenBIC pull request #1105
Opened 2023-05-18 16:57 UTC by DelphineChiu

# Description
1. Add a lock to limit one thread to purge mqueue when queue is full, avoid the race condition.
2. Set timeout in IPMI handler to avoid one command block the thread for a long time.

# Motivation
IPMB message queue will be full if multiple commands stuck for a long time.

# Test plan
Build and test pass on fby35 system.
1. IPMI/IPMB works normal root@bmc-oob:~# fw-util slot1 --force --update bic Y35BCL.bin There is no valid platform signature in image.
slot_id: 1, comp: 2, intf: 0, img: Y35BCL.bin, force: 1 file size = 294364 bytes, slot = 1, intf = 0xff
updating fw on slot 1:
updated bic: 100 %
Elapsed time:  5   sec.

get new SDR cache from BIC
Force upgrade of slot1 : bic succeeded

2023-05-19 00:16 UTC, jagpalgill requested changes

2023-05-19 00:16 UTC, jagpalgill commented on common/service/host/kcs.c
>  				k_msgq_purge(&ipmi_msgq);
@DelphineChiu  Drop purge as its already take care by ipmb_notify_client?

2023-05-19 00:16 UTC, jagpalgill commented on common/service/ipmb/ipmb.c
> +static struct k_mutex mutex_send_req[MAX_IPMB_IDX], mutex_send_res, mutex_read, mutex_put_msgq;
@DelphineChiu Rename this mutex to mutex_purge_msgq since it creates critical section for get msgq size and purge msgq?

2023-05-22 02:49 UTC, Andy-wiwynn commented
Hi @jagpalgill ,
The code is updated based on your suggestion, please help to review again. Thanks.

2023-05-22 17:24 UTC, closed without merging