Artemis: cb: Support power brick second source sensor reading
facebook/OpenBIC pull request #1177
Opened 2023-06-15 10:07 UTC by MarshallZhan-wiwynn

# Description
- Support power brick second source(BMR351) sensor reading.

# Motivation
- Support power brick second source sensor reading.

# Test Plan
- Build code: Pass
- Get power brick(Q50SN120A1) sensor reading: Pass

# Log
CB_POWER_BRICK_1_TEMP_C      (0x9) :   28.00 C     | (ok)
CB_POWER_BRICK_2_TEMP_C      (0xA) :   30.00 C     | (ok)
CB_P12V_AUX_1_V              (0xD) :   12.17 Volts | (ok)
CB_P12V_AUX_2_V              (0xE) :   12.16 Volts | (ok)
CB_P12V_AUX_1_A              (0x32) :    3.50 Amps  | (ok)
CB_P12V_AUX_2_A              (0x33) :    3.75 Amps  | (ok)
CB_P12V_AUX_1_W              (0x43) :   39.55 Watts | (ok)
CB_P12V_AUX_2_W              (0x44) :   57.76 Watts | (ok)

2023-06-15 10:53 UTC, LoraLin1 commented
Hi Meta,

The issue report by reviewdog：
Reviewdog thinks plat_monitor_sensor_count will only be zero.

The plat_monitor_sensor_count is assigned by pal_get_monitor_sensor_count function.
Since pal_get_monitor_sensor_count is a weak function in sensor.c file, it will be overwritten when Artemis ACB defines this function, so plat_monitor_sensor_count may not be zero.

Regards,
Lora.

2023-06-16 21:35 UTC, wangx6f requested changes
There is merge conflict for the following files:
`common/service/sensor/sensor.h`
`meta-facebook/at-cb/src/platform/plat_sensor_table.c`
Please rebase.

2023-06-19 00:43 UTC, LoraLin1 commented
Hi @wangx6f ,
We have fixed the confliict and do the force update.
Please help to review again, thank you.

Regards,
Lora.

2023-06-21 22:35 UTC, jagpalgill commented on common/dev/bmr351.c
> +		break;
Do we need a break after return?

2023-06-21 22:35 UTC, jagpalgill commented on common/dev/bmr351.c
> +int bmr351_read_pout(sensor_cfg *cfg, float *pout_value)
Better to define this func as static.

2023-06-21 22:35 UTC, jagpalgill commented on common/dev/bmr351.c
> +	CHECK_NULL_ARG_WITH_RETURN(pout_value, -1);
If there is no warning in case you skip this check, then its better to skip it since in caller its a variable on stack.

2023-06-21 22:35 UTC, jagpalgill commented on common/dev/bmr351.c
> +	CHECK_NULL_ARG_WITH_RETURN(cfg, -1);
If there is no warning in case you skip this check, then its better to skip it since caller already checks for it.

2023-06-26 02:16 UTC, LoraLin1 commented
Hi @jagpalgill ,
Thanks for your comments.
Based on your suggestions to modify the code, rebase main and force update the branch.
Please help to review it again, thank you.

Regards,
Lora.

2023-06-26 21:30 UTC, closed without merging