fby35: gl: Support DIMM and PMIC reading via I3C
facebook/OpenBIC pull request #1292
Opened 2023-08-18 02:01 UTC by BonnieLo

# Description:
Read DIMM related data (DIMM's temperature, PMIC power, and PMIC error) by I3C

# Motivation:
Currently, BIC read DIMM by using PECI command

# Test Plan:
1. Check DIMM temperature and PMIC power sensors - pass
2. Inject PMIC error and check SEL - pass

# Test Log:
1. Check DIMM temperature and PMIC power sensors root@bmc-oob:~# sensor-util slot1|grep -i DIMM
MB_DIMMA_TEMP_C              (0x5) :   34.50 C     | (ok)
MB_DIMMB_TEMP_C              (0x6) :   33.00 C     | (ok)
MB_DIMMC_TEMP_C              (0x7) :   33.25 C     | (ok)
MB_DIMMD_TEMP_C              (0x8) :   33.25 C     | (ok)
MB_DIMME_TEMP_C              (0x9) :   33.50 C     | (ok)
MB_DIMMF_TEMP_C              (0xA) :   33.00 C     | (ok)
MB_DIMMG_TEMP_C              (0xB) :   33.25 C     | (ok)
MB_DIMMH_TEMP_C              (0xC) :   33.00 C     | (ok)
MB_ADC_P12V_DIMM_VOLT_V      (0x25) :   12.36 Volts | (ok)
MB_VR_DIMMA_PMIC_PWR_W       (0x36) :    1.12 Watts | (ok)
MB_VR_DIMMB_PMIC_PWR_W       (0x37) :    0.62 Watts | (ok)
MB_VR_DIMMC_PMIC_PWR_W       (0x38) :    0.75 Watts | (ok)
MB_VR_DIMMD_PMIC_PWR_W       (0x39) :    0.50 Watts | (ok)
MB_VR_DIMME_PMIC_PWR_W       (0x3A) :    0.62 Watts | (ok)
MB_VR_DIMMF_PMIC_PWR_W       (0x3B) :    1.00 Watts | (ok)
MB_VR_DIMMG_PMIC_PWR_W       (0x3C) :    0.75 Watts | (ok)
MB_VR_DIMMH_PMIC_PWR_W       (0x3D) :    0.50 Watts | (ok)

2. Inject PMIC error and check SEL
- Inject DIMM warning error high_temp on DIMM A root@bmc-oob:~# log-util slot1 --print|grep -i ipmid
1    slot1    2023-08-15 14:02:15    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2023-08-15 14:02:14, Sensor: PMIC_ERR (0xB4), Event Data: (000C00) DIMM A High Temp Warning Assertion

2023-08-21 18:29 UTC, williamspatrick requested changes

2023-08-22 02:30 UTC, WayneLiu-wiwynn commented on common/hal/hal_i3c.c
> +			*pos = i;
OK.
I have followed the first option to revise.

2023-08-22 11:25 UTC, williamspatrick requested changes

2023-08-22 11:25 UTC, williamspatrick commented on common/hal/hal_i3c.c
> +			*pos = i;
Don’t we need a null pointer check in this function then?

2023-08-22 18:36 UTC, jagpalgill commented on common/hal/hal_i3c.c
> +	desc = find_matching_desc(dev_i3c[msg->bus], msg->target_addr, &pos);
I suppose we need a NULL check for desc as well?

2023-08-22 18:36 UTC, jagpalgill commented on meta-facebook/yv35-gl/src/platform/plat_dimm.c
> +			LOG_ERR("Failed to lock I3C dimm MUX");
Do you still want to continue if lock failed?

2023-08-22 18:36 UTC, jagpalgill commented on meta-facebook/yv35-gl/src/platform/plat_dimm.c
> +	return false;
You are retuning a false for a success case too i suppose, is that fine?

2023-08-23 16:42 UTC, closed without merging