fby4 - Support get/set gpio through PLDM
facebook/OpenBIC pull request #1307
Opened 2023-08-23 08:17 UTC by EliHuang-wiwynn

Summary:
Description
- Initialize fby4 gpio table by referencing BIC_GPIO_20230810.
- Initialization MCTP and PLDM assign gpio effecter ID.
- Add PLDM set/get state effecter state handler.

Motivation
- Support get/set gpio through PLDM on fby4

Test Plan:
- Build code: Pass
- Set/Get gpio: Pass

Test Log:
1 . Get gpio 0x5 (0xFF05)
[BIC]
md 0x7E780000 1
[7e780000] e65e125b
[BMC]
root@greatlakes:~# pldmtool raw -d 0x80 0x02 0x3a 0x05 0xff pldmtool: Tx: 80 02 3a 05 ff
pldmtool: Rx: 00 02 3a 00 02 01 02 02 01 01 01

2. Set GPIOA5 value root@greatlakes:~# pldmtool raw -d 0x80 0x02 0x39 0x05 0xff 0x02 0x00 0x00 0x00 0x02 pldmtool: Tx: 80 02 39 05 ff 02 00 00 00 02
pldmtool: Rx: 00 02 39 00

3. Get GPIOA5 value [BIC]
md 0x7E780000 1
[7e780000] e65e127b
[BMC]
root@greatlakes:~# pldmtool raw -d 0x80 0x02 0x3a 0x05 0xff pldmtool: Tx: 80 02 3a 05 ff
pldmtool: Rx: 00 02 3a 00 02 01 02 02 01 02 02

2023-08-24 22:35 UTC, jagpalgill commented
Majority of the code in pldm_monitor.h and pldm_monitor.c can be moved into common layer as common pldm code so other platforms can use it too. Platform specific code in this case should just have bunch of tables with platform specific info. Can you please revisit this changeset from that perspective and make necessary changes?

2023-08-24 22:36 UTC, jagpalgill requested changes

2023-08-24 22:36 UTC, jagpalgill commented on meta-facebook/yv4-sd/src/platform/plat_pldm_monitor.c
> +/*
Majority of the code in pldm_monitor.h and pldm_monitor.c can be moved into common layer as common pldm code so other platforms can use it too. Platform specific code in this case should just have bunch of tables with platform specific info. Can you please revisit this changeset from that perspective and make necessary changes?

2023-09-01 06:16 UTC, EliHuang-wiwynn commented
This PR has dependency so we close this PR until #1304 #1303 is merged.

2023-09-11 17:49 UTC, closed without merging