yv4: sd: Support entity auxiliary name PDR
facebook/OpenBIC pull request #1926
Opened 2024-08-20 00:44 UTC by BonnieLo

# Description:
Support entity auxiliary name PDR with container ID 0x0000, which will be terminus name in pldmd in BMC.

# Motivation:
Upstream pldm sensor had be coded to regard the terminus name as mandatory. It's now utilizing entity auxiliary name PDR with container ID 0x0000 to get terminus name or from Entity Manager configuration(not implemented).

# Test Plan:
Build code - pass
Tested on YV4 - pass

# Test Log:
...
        ├─ /xyz/openbmc_project/sensors/voltage/Sentinel_Dome_Slot_3_MB_ADC_P12V_DIMM_0_VOLT_V
        ├─ /xyz/openbmc_project/sensors/voltage/Sentinel_Dome_Slot_3_MB_ADC_P12V_DIMM_1_VOLT_V
        ├─ /xyz/openbmc_project/sensors/voltage/Sentinel_Dome_Slot_3_MB_ADC_P12V_STBY_VOLT_V
        ├─ /xyz/openbmc_project/sensors/voltage/Sentinel_Dome_Slot_3_MB_ADC_P1V2_STBY_VOLT_V
        ├─ /xyz/openbmc_project/sensors/voltage/Sentinel_Dome_Slot_3_MB_ADC_P1V8_STBY_VOLT_V
        ├─ /xyz/openbmc_project/sensors/voltage/Sentinel_Dome_Slot_3_MB_ADC_P3V3_STBY_VOLT_V
...

2024-08-22 18:25 UTC, Prabha-Veerubhotla commented
@BonnieLo can you fix the run-cppcheck error.

2024-08-23 18:48 UTC, Prabha-Veerubhotla requested changes
please fix the run-cppcheck error.

2024-08-26 02:13 UTC, PeterHo-wiwynn commented
Hi @Prabha-Veerubhotla, It seems like cppcheck error is causing by we having some function implemented in platform code. It is expected because we will need to keep default value in common layer and define them in platform layer.

2024-08-29 06:47 UTC, DelphineChiu commented
Hi @Prabha-Veerubhotla  Patrick to release yv4 BMC firmware by this week and this commit is critical to the compabililty with BMC firmware. Do you still have concern about the reply of CI error.  cc @williamspatrick

2024-08-30 18:08 UTC, closed without merging