main_v2 - fby3.5: cl: new sensor reading structure and support MP5990 sensor reading
facebook/OpenBIC pull request #229
Opened 2022-04-15 07:43 UTC by DelphineChiu

Summary:
- common: Phase in new sensor reading structure with README file
- fby3.5: cl: Support MP5990 sensor reading

2022-04-15 19:08 UTC, GoldenBug requested changes

2022-04-18 09:42 UTC, RenChen-wiwynn commented on common/dev/adm1278.c
> +	    (sensor_config[sensor_config_index_map[sensor_num]].init_args == NULL)) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:42 UTC, RenChen-wiwynn commented on common/dev/adm1278.c
> +	if (!sensor_config[sensor_config_index_map[sensor_num]].init_args) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:43 UTC, RenChen-wiwynn commented on common/dev/adm1278.c
> +uint8_t adm1278_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:43 UTC, RenChen-wiwynn commented on common/dev/adm1278.c
> +	if (!sensor_config[sensor_config_index_map[sensor_num]].init_args) {
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:43 UTC, RenChen-wiwynn commented on common/dev/ast_adc.c
> +	int err, retval;
We have fixed this and do the forced update.
Please review it. Thanks.

2022-04-18 09:43 UTC, RenChen-wiwynn commented on common/dev/ast_adc.c
> +	if (!sensor_config[sensor_config_index_map[sensor_num]].init_args) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:43 UTC, RenChen-wiwynn commented on common/dev/intel_peci.c
> +	if (peci_retry_read(PECI_CMD_RD_PKG_CFG0, addr, RDPKG_IDX_TJMAX_TEMP, param, rlen, rbuf) ==
We have fixed this and do the forced update.
Please review it. Thanks.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/intel_peci.c
> +	if (peci_retry_read(PECI_CMD_RD_PKG_CFG0, addr, RDPKG_IDX_PKG_TEMP, param, rlen, rbuf) ==
We have fixed this and do the forced update.
Please review it. Thanks.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/isl28022.c
> +	    (sensor_config[sensor_config_index_map[sensor_num]].init_args == NULL)) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/isl28022.c
> +	if (sensor_config[sensor_config_index_map[sensor_num]].init_args == NULL) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/isl69259.c
> +	msg.bus = sensor_config[sensor_config_index_map[sensor_num]].port;
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/ltc4282.c
> +	    (sensor_config[sensor_config_index_map[sensor_num]].init_args == NULL)) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/ltc4282.c
> +uint8_t ltc4282_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/isl28022.c
> +uint8_t isl28022_init(uint8_t sensor_num)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/isl28022.c
> +uint8_t isl28022_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:44 UTC, RenChen-wiwynn commented on common/dev/ltc4282.c
> +uint8_t ltc4282_init(uint8_t sensor_num)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:45 UTC, RenChen-wiwynn commented on common/dev/mp5990.c
> +uint8_t mp5990_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:45 UTC, RenChen-wiwynn commented on common/dev/mp5990.c
> +uint8_t mp5990_init(uint8_t sensor_num)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:45 UTC, RenChen-wiwynn commented on common/dev/mp5990.c
> +	    (sensor_config[sensor_config_index_map[sensor_num]].init_args == NULL)) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:45 UTC, RenChen-wiwynn commented on common/dev/mp5990.c
> +	if (!sensor_config[sensor_config_index_map[sensor_num]].init_args) {
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/nvme.c
> +uint8_t nvme_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/pch.c
> +uint8_t pch_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/pex89000.c
> +uint8_t pex89000_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/tmp75.c
> +uint8_t tmp75_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/tps53689.c
> +uint8_t tps53689_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/xdpe15284.c
> +uint8_t xdpe15284_read(uint8_t sensor_num, int *reading)
We have fixed this and do the forced update.
The sensor_num is unsigned type so only judge if it's less than MAX_NUM_SENSORS.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/lib/util_pmbus.c
> +bool get_exponent_from_vout_mode(uint8_t sensor_num, float *exponent)
We have fixed this and do the forced update.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/nvme.c
> +			return SENSOR_UNSPECIFIED_ERROR;
We have fixed this and do the forced update.
Please review it. Thanks.

2022-04-18 09:46 UTC, RenChen-wiwynn commented on common/dev/nvme.c
> +	} else
We have fixed this and do the forced update.
Please review it. Thanks.

2022-04-18 09:47 UTC, RenChen-wiwynn commented on common/dev/pex89000.c
> +		(pex89000_init_arg *)sensor_config[sensor_config_index_map[sensor_num]].init_args;
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:47 UTC, RenChen-wiwynn commented on common/dev/tmp75.c
> +	msg.bus = sensor_config[sensor_config_index_map[sensor_num]].port;
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:47 UTC, RenChen-wiwynn commented on common/dev/tps53689.c
> +	msg.bus = sensor_config[sensor_config_index_map[sensor_num]].port;
The stack memory is limited to BIC.
The size of sensor_cfg is 60 bytes.
So, we propose not to define a temporary variable.

2022-04-18 09:47 UTC, RenChen-wiwynn commented on common/dev/pex89000.c
> +	}
We have fixed this and do the forced update.
Please review it. Thanks.

2022-04-19 02:49 UTC, DelphineChiu commented
close the PR since the codes have been merged

2022-04-19 02:49 UTC, closed without merging