fby3.5: common:Fix sensor monitor memcpy fail causing BIC crash issue
facebook/OpenBIC pull request #349
Opened 2022-06-21 02:00 UTC by DelphineChiu

Summary:
- Fix sensor monitor memcpy fail causing BIC crash issue
  - Check SDR/sensor config table size before memcpy SDR/sensor config from platform to common.
    If SDR size not equal to sensor config size, BIC would not allocate SDR/sensor config table and monitor sensor.
- Improve sensor monitor
  - Array Config D BB BIC full_sdr_table: remove redundancy SDR.
  - Array full_sdr_table: allocate memory size according to different cards present.
  - Function add_full_sdr_table: check SDR table size before adding SDR.
  - Function add_sensor_config: check config table size before adding sensor config.
  - Function get_sensor_reading: check sensor information in sensor config table.
  - Variable sensor_config_num: modify variable name to sensor_config_count making name more readable.
  - Command platform: fix BIC crash when sensor list_all command fail to map sensor information.

Dependency: #339 

Test Plan:
- Build code: Pass
- Check BIC status in error case with Config A/B/C/D: Pass
- Check sensor monitor in error case with Config A/B/C/D: Pass

error case                                            error handling
--------------------------------------------------------------------------------------------------------------------------------------------
SDR table size is not equal to config table size      Do not allocate memory to SDR/sensor config table, and BIC would not monitor sensor.
sensor monitor number doesn't match with SDR table    Print "[sensor_poll_handler] fail to find sensor SDR info, sensor number: 0xXX" and sensor would monitor this sensor,
                                                      if config table sensor number is not found in SDR table.
                                                      Print "[get_sensor_reading] fail to find sensor info in config table, sensor_num: 0xXX" and sensor would show NA on sensor-util,
                                                      if sdr table sensor number is not found in config table.
Log:
[normal case]

[BMC console]
root@bmc-oob:~# sensor-util slot2 --threshold
slot2:
MB Inlet Temp                (0x1) :   32.00 C     | (ok) | UCR: 48.00 | UNC: NA | UNR: 150.00 | LCR: NA | LNC: NA | LNR: NA
MB Outlet Temp               (0x2) :   49.00 C     | (ok) | UCR: 93.00 | UNC: NA | UNR: 150.00 | LCR: NA | LNC: NA | LNR: NA
FIO Temp                     (0x3) :   29.00 C     | (ok) | UCR: 40.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
PCH Temp                     (0x4) :   45.00 C     | (ok) | UCR: 74.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
SOC CPU Temp                 (0x5) :   44.00 C     | (ok) | UCR: 84.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
SOC Therm Margin             (0x14) :  -56.00 C     | (ok) | UCR: NA | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
CPU TjMax                    (0x15) :  100.00 C     | (ok) | UCR: NA | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
DIMMA Temp                   (0x6) :   46.00 C     | (ok) | UCR: 85.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
DIMMC Temp                   (0x7) :   46.00 C     | (ok) | UCR: 85.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
DIMMD Temp                   (0x9) :   43.00 C     | (ok) | UCR: 85.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
DIMME Temp                   (0xA) :   45.00 C     | (ok) | UCR: 85.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
DIMMG Temp                   (0xB) :   42.00 C     | (ok) | UCR: 85.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
DIMMH Temp                   (0xC) :   38.00 C     | (ok) | UCR: 85.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
SSD0 Temp                    (0xD) :   34.00 C     | (ok) | UCR: 75.00 | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
HSC Temp                     (0xE) :   45.95 C     | (ok) | UCR: 86.00 | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
VCCIN SPS Temp               (0xF) :   57.00 C     | (ok) | UCR: 100.00 | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
FIVRA SPS Temp               (0x10) :   54.00 C     | (ok) | UCR: 100.00 | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
EHV SPS Temp                 (0x11) :   45.00 C     | (ok) | UCR: 100.00 | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
VCCD SPS Temp                (0x12) :   43.00 C     | (ok) | UCR: 100.00 | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
FAON SPS Temp                (0x13) :   47.00 C     | (ok) | UCR: 100.00 | UNC: NA | UNR: 125.00 | LCR: NA | LNC: NA | LNR: NA
P12V_STBY Vol                (0x20) :   12.68 Volts | (ok) | UCR: 13.36 | UNC: 13.23 | UNR: 14.36 | LCR: 10.71 | LNC: 10.84 | LNR: 10.08
P3V_BAT Vol                  (0x21) :    3.13 Volts | (ok) | UCR: 3.51 | UNC: 3.46 | UNR: NA | LCR: 2.76 | LNC: 2.79 | LNR: NA
P3V3_STBY Vol                (0x22) :    3.34 Volts | (ok) | UCR: 3.56 | UNC: 3.53 | UNR: 4.00 | LCR: 3.04 | LNC: 3.08 | LNR: 2.30
P1V8_STBY Vol                (0x23) :    1.81 Volts | (ok) | UCR: 1.92 | UNC: 1.90 | UNR: 2.09 | LCR: 1.67 | LNC: 1.69 | LNR: 1.44
P1V05_PCH Vol                (0x24) :    1.06 Volts | (ok) | UCR: 1.12 | UNC: 1.10 | UNR: 1.22 | LCR: 0.97 | LNC: 0.98 | LNR: 0.84
P5V_STBY Vol                 (0x25) :    5.02 Volts | (ok) | UCR: 5.40 | UNC: 5.35 | UNR: 5.80 | LCR: 4.59 | LNC: 4.64 | LNR: 4.00
P12V_DIMM Vol                (0x26) :   12.73 Volts | (ok) | UCR: 14.21 | UNC: 14.07 | UNR: NA | LCR: 9.87 | LNC: 10.01 | LNR: NA
P1V2_STBY Vol                (0x27) :    1.20 Volts | (ok) | UCR: 1.30 | UNC: 1.28 | UNR: 1.39 | LCR: 1.10 | LNC: 1.12 | LNR: 0.96
P3V3_M2 Vol                  (0x28) :    3.33 Volts | (ok) | UCR: 3.71 | UNC: 3.67 | UNR: NA | LCR: 2.91 | LNC: 2.94 | LNR: NA
HSC Input Vol                (0x29) :   12.51 Volts | (ok) | UCR: 13.36 | UNC: 13.23 | UNR: 14.36 | LCR: 10.71 | LNC: 10.84 | LNR: 10.08
VCCIN VR Vol                 (0x2A) :    1.77 Volts | (ok) | UCR: 1.93 | UNC: 1.91 | UNR: 2.20 | LCR: 1.64 | LNC: 1.66 | LNR: 0.40
FIVRA VR Vol                 (0x2C) :    1.82 Volts | (ok) | UCR: 1.92 | UNC: 1.90 | UNR: 2.20 | LCR: 1.69 | LNC: 1.71 | LNR: 0.40
EHV VR Vol                   (0x2D) :    1.80 Volts | (ok) | UCR: 1.90 | UNC: 1.88 | UNR: 2.20 | LCR: 1.70 | LNC: 1.72 | LNR: 0.40
VCCD VR Vol                  (0x2E) :    1.14 Volts | (ok) | UCR: 1.23 | UNC: 1.21 | UNR: 1.50 | LCR: 1.05 | LNC: 1.06 | LNR: 0.40
FAON VR Vol                  (0x2F) :    1.05 Volts | (ok) | UCR: 1.09 | UNC: 1.07 | UNR: 1.40 | LCR: 0.90 | LNC: 0.91 | LNR: 0.40
HSC Output Cur               (0x30) :    7.52 Amps  | (ok) | UCR: 31.96 | UNC: 28.73 | UNR: 39.95 | LCR: NA | LNC: NA | LNR: NA
VCCIN VR Cur                 (0x31) :   29.80 Amps  | (ok) | UCR: 141.18 | UNC: 119.34 | UNR: 180.18 | LCR: NA | LNC: NA | LNR: NA
FIVRA VR Cur                 (0x32) :    3.60 Amps  | (ok) | UCR: 53.01 | UNC: 48.05 | UNR: 70.99 | LCR: NA | LNC: NA | LNR: NA
EHV VR Cur                   (0x33) :    0.80 Amps  | (ok) | UCR: 6.24 | UNC: 5.04 | UNR: 18.00 | LCR: NA | LNC: NA | LNR: NA
VCCD VR Cur                  (0x34) :    2.60 Amps  | (ok) | UCR: 30.02 | UNC: 26.98 | UNR: 42.94 | LCR: NA | LNC: NA | LNR: NA
FAON VR Cur                  (0x35) :    8.70 Amps  | (ok) | UCR: 46.02 | UNC: 42.12 | UNR: 60.06 | LCR: NA | LNC: NA | LNR: NA
CPU PWR                      (0x38) :   55.00 Watts | (ok) | UCR: NA | UNC: NA | UNR: NA | LCR: NA | LNC: NA | LNR: NA
HSC Input Pwr                (0x39) :   90.08 Watts | (ok) | UCR: 399.28 | UNC: 360.22 | UNR: 499.10 | LCR: NA | LNC: NA | LNR: NA
VCCIN VR Pout                (0x3A) :   24.00 Watts | (ok) | UCR: 253.80 | UNC: 214.32 | UNR: 324.30 | LCR: NA | LNC: NA | LNR: NA
FIVRA VR Pout                (0x3C) :    5.00 Watts | (ok) | UCR: 95.19 | UNC: 86.64 | UNR: 127.68 | LCR: NA | LNC: NA | LNR: NA
EHV VR Pout                  (0x3D) :    1.00 Watts | (ok) | UCR: 11.25 | UNC: 8.97 | UNR: 32.38 | LCR: NA | LNC: NA | LNR: NA
VCCD VR Pout                 (0x3E) :    2.00 Watts | (ok) | UCR: 34.32 | UNC: 31. [...]

2022-06-21 02:00 UTC, DelphineChiu commented
Dependency: #339

2022-06-22 00:46 UTC, LoraLin1 commented
Hi @GoldenBug 
We have fixed the conflict and do the forced update.
Please review it. Thanks.

2022-06-22 23:49 UTC, GoldenBug requested changes
Many changes more than I requested but if we are going to change `full_sdr_table` to a pointer instead of a statically allocated array then we need to check to make sure full_sdr_table isn't null everywhere we want to use it.

2022-06-23 00:07 UTC, DelphineChiu commented on common/service/sensor/sdr.c
> -	printf("Function %s is not implemented\n", __func__);
@GoldenBug For the BIC which doesn't need to run into this pal function, for example, RF/WF BIC, I think this messages will confuse and think about something wrong. BMC firmware common code also doesn't add the messages in common layer.

2022-06-23 00:58 UTC, LoraLin1 commented on common/service/sensor/sdr.c
> +		memcpy(&full_sdr_table[index], &add_item, sizeof(SDR_Full_sensor));
@GoldenBug 
We add the judgment condition for checking NULL pointer and fix the conflict.
Please review it. Thanks.

2022-06-23 00:59 UTC, LoraLin1 commented on common/service/sensor/sdr.c
> +		if (sensor_num == full_sdr_table[i].sensor_num) {
Hi @GoldenBug 
We add the judgment condition for checking NULL pointer and fix the conflict.
Please review it. Thanks.

2022-06-23 17:22 UTC, closed without merging