GT: Add shell command to stress E1.S power
facebook/OpenBIC pull request #395
Opened 2022-07-11 12:19 UTC by Quanta-YangChen

Summary:
- Add command to stress E1.S power according to SIT testing requirements.
- Follow by NVME cloud ssd specification v1.0.3 chapter 9.2 as below link:
https://www.opencompute.org/documents/nvme-cloud-ssd-specification-v1-0-3-pdf
- Print the average value of the power consumption on a given device id in a 250 ms window with a sampling rate of 2 ms in a given duration.
- Usage in BIC console:
	test e1s power [device index] [duration (minute)]

Test plan:
- Build code: Pass

Log:
uart:\~$  test e1s power 0 1
==== Start stress E1S dev0 power consumption 1 minutes =====
uart:\~$ E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.29 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.30 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.22 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.23 Watts
E1S dev0 power avg = 3.22 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.23 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.20 Watts
E1S dev0 power avg = 3.22 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.21 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.21 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.29 Watts
E1S dev0 power avg = 3.30 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.22 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.19 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.30 Watts
E1S dev0 power avg = 3.23 Watts
E1S dev0 power avg = 3.21 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.19 Watts
E1S dev0 power avg = 3.21 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.31 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.29 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.23 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.19 Watts
E1S dev0 power avg = 3.21 Watts
E1S dev0 power avg = 3.20 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.30 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.30 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.23 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.21 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.29 Watts
E1S dev0 power avg = 3.27 Watts
E1S dev0 power avg = 3.23 Watts
E1S dev0 power avg = 3.22 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.22 Watts
E1S dev0 power avg = 3.26 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.25 Watts
E1S dev0 power avg = 3.28 Watts
E1S dev0 power avg = 3.22 Watts
E1S dev0 power avg = 3.24 Watts
E1S dev0 power avg = 3.23 Watts
E1S dev0 power avg = 3.20 Watts
==== Stop stress E1S dev0 power consumption ====

2022-07-12 07:13 UTC, GoldenBug commented
Could you seperate these changes into seperate files.

1. A new directory under the platform directory `src/shell/` that has a header and c file implimenting the tests.
2. Then in the plat_shell.c file only add the subcommands.

Otherwise in the future the plat_shell file might grow very large for any platform with many commands.

2022-07-12 07:16 UTC, GoldenBug requested changes

2022-07-12 07:16 UTC, GoldenBug commented on meta-facebook/gt-cc/src/platform/plat_shell.c
> +	printf("==== Start stress E1S dev%d power consumption %d minutes =====\n", e1s_idx,
shell_print(...)

2022-07-12 07:16 UTC, GoldenBug commented on meta-facebook/gt-cc/src/platform/plat_shell.c
> +		printf("==== Stop stress E1S dev%d power consumption ==== \n", data->e1s_idx);
shell_print(...)

2022-07-12 07:16 UTC, GoldenBug commented on meta-facebook/gt-cc/src/platform/plat_shell.c
> +		printf("E1S dev%d power avg = %.2f Watts\n", data->e1s_idx, avg);
shell_print(...)

2022-07-12 07:16 UTC, GoldenBug commented on meta-facebook/gt-cc/src/platform/plat_shell.c
> +			printf("[%s] Reading E1S dev%d power failed \n", __func__, data->e1s_idx);
shell_print(...)

2022-07-13 02:23 UTC, Quanta-YangChen commented
Hi @GoldenBug,
We change the code by your suggestion and rebase from the main branch then do the force push. Please help to review again, thanks.

2022-07-14 20:22 UTC, closed without merging