Fby3.5 hd support bom3 sensor
facebook/OpenBIC pull request #468
Opened 2022-08-05 07:32 UTC by Yi-Shum

Summary:
- Support VR sensor MP2856GUT
- Add the sensor config table of 3rd source sensor, replace sensor talbe to it if board revision is SYS_BOARD_EVT_BOM3.

Dependency: #467 

Test Plan:
- Build Code: Pass

Known issue:
- Pout reading for MP2856GUT is larger than expected, still checking with FAE.

Log:
Third source boar
```
root@bmc-oob:~# sensor-util slot1
...
HSC Temp                     (0xE) :   47.12 C     | (ok)
CPU0 VR Temp                 (0xF) :   49.00 C     | (ok)
SOC VR Temp                  (0x10) :   51.00 C     | (ok)
CPU1 VR Temp                 (0x11) :   34.00 C     | (ok)
PVDDIO VR Temp               (0x12) :   34.00 C     | (ok)
PVDD11 VR Temp               (0x13) :   31.00 C     | (ok)
P12V_STBY Vol                (0x14) :   12.00 Volts | (ok)
PVDD18_S5 Vol                (0x15) :    1.81 Volts | (ok)
P3V3_STBY Vol                (0x16) :    3.30 Volts | (ok)
PVDD11_S3 Vol                (0x17) :    1.10 Volts | (ok)
P3V_BAT Vol                  (0x18) :    3.08 Volts | (ok)
PVDD33_S5 Vol                (0x19) :    3.31 Volts | (ok)
P5V_STBY Vol                 (0x1A) :    4.99 Volts | (ok)
P12V_MEM_1 Vol               (0x1B) :   12.05 Volts | (ok)
P12V_MEM_0 Vol               (0x1C) :   12.03 Volts | (ok)
P1V2_STBY Vol                (0x1D) :    1.20 Volts | (ok)
P3V3_M2 Vol                  (0x1E) :    3.31 Volts | (ok)
P1V8_STBY Vol                (0x1F) :    1.81 Volts | (ok)
HSC Input Vol                (0x20) :   12.05 Volts | (ok)
CPU0 VR Vol                  (0x21) :    0.92 Volts | (ok)
SOC VR Vol                   (0x22) :    1.19 Volts | (ok)
CPU1 VR Vol                  (0x23) :    0.93 Volts | (ok)
PVDDIO VR Vol                (0x24) :    1.10 Volts | (ok)
PVDD11 VR Vol                (0x25) :    1.10 Volts | (ok)
HSC Output Cur               (0x26) :   12.75 Amps  | (ok)
CPU0 VR Cur                  (0x27) :   12.75 Amps  | (ok)
SOC VR Cur                   (0x28) :   59.75 Amps  | (ok)
CPU1 VR Cur                  (0x29) :   16.75 Amps  | (ok)
PVDDIO VR Cur                (0x2A) :   31.75 Amps  | (ok)
PVDD11 VR Cur                (0x2B) :    3.25 Amps  | (ok)
HSC Input Pwr                (0x2C) :  155.15 Watts | (ok)
CPU0 VR Pwr                  (0x2D) :   96.00 Watts | (ok)
SOC VR Pwr                   (0x2E) :  568.00 Watts | (ucr)
CPU1 VR Pwr                  (0x2F) :  120.00 Watts | (ok)
PVDDIO VR Pwr                (0x30) :  280.00 Watts | (ucr)
PVDD11 VR Pwr                (0x31) :   32.00 Watts | (ok)
...
```

2022-08-05 17:28 UTC, garnermic requested changes
Few minor changes requested.  Thanks!

2022-08-05 17:28 UTC, garnermic commented on common/shell/shell_platform.h
> +			sensor_name_to_num(xdpe15284) sensor_name_to_num(ltc4282) sensor_name_to_num(
Please reformat to make this section easier to read.

2022-08-05 17:28 UTC, garnermic commented on meta-facebook/yv35-hd/src/platform/plat_class.c
> +		}
Please add an else to capture invalid hsc_module value.

2022-08-05 17:28 UTC, garnermic commented on meta-facebook/yv35-hd/src/platform/plat_class.c
> +	}
Add an else statemetn here or change else-if to else if it handles all failure cases.

2022-08-08 10:11 UTC, Yi-Shum commented
Hi @garnermic ,
I modified it based on the comments.
Please review again, thank you.

2022-08-12 08:09 UTC, Yi-Shum commented
Close this PR since HSC OCP setting will be changed.
Will create another PR to support BOM3 sensor.

2022-08-12 08:09 UTC, closed without merging