fby35: common: Support i2c mux PCA9846
facebook/OpenBIC pull request #543
Opened 2022-09-12 02:27 UTC by DelphineChiu

Summary:
- Add device i2c-mux-PCA9846 common function to set channel and transfer i2c message.

Test Plan and Log:
1. Y35 CL/Y35 BB/Y35 RF/GT CC/YV3 DL BIC build code: Pass
2. Set mux to switch channel: Pass

  - Origin i2c bus 8, i2c mux PCA9846 slave address is 0x71 uart:~$ i2c scan I2C_8 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
  00:             -- -- -- -- -- -- -- -- -- -- -- --
  10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  70: -- 71 -- -- -- -- -- --
  1 devices found on I2C_8

  - Set mux to switch to channel 0 uart:~$ i2c scan I2C_8 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
  00:             -- -- -- -- -- -- -- -- -- -- -- --
  10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  40: -- -- -- -- -- 45 -- -- -- -- -- -- -- -- -- --
  50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  70: -- 71 -- -- -- -- -- --
  2 devices found on I2C_8

  - Set mux to switch to channel 1 uart:~$ i2c scan I2C_8 0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
  00:             -- -- -- -- -- -- -- -- -- -- -- --
  10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  40: 40 41 -- 43 -- -- -- -- -- -- -- -- -- -- -- --
  50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  70: -- 71 -- -- -- -- -- --
  4 devices found on I2C_8

3. Mutex lock/unlock: Pass

  - Trigger GPIO thread enter queue for locking mutex, setting channel, transfering message and unlocking mutex.
  root@bmc-oob:~# bic-util slot1 --set_gpio 0 0     // Set mux to switch to channel 0
  slot 1: setting [0]FM_BMC_PCH_SCI_LPC_R_N to 0
  root@bmc-oob:~# bic-util slot1 --set_gpio 47 0    // Set mux to switch to channel 1
  slot 1: setting [47]FBRK_N_R to 0

  [ BIC console ]

  [ISR_SET_CHANNEL_0] set channel 0
  [set_pca9846_channel_and_transfer] lock start, count: 0x1
  [set_pca9846_channel_and_transfer] lock done
  [set_pca9846_channel_and_transfer] transfer data success
  [set_pca9846_channel_and_transfer] disable all channel and unlock, count: 0x0
  [set_pca9846_channel_and_transfer] device response data [0] [0]
  [ISR_SET_CHANNEL_0] success

  [ISR_SET_CHANNEL_1] set channel 1
  [set_pca9846_channel_and_transfer] lock start, count: 0x1
  [set_pca9846_channel_and_transfer] lock done
  [set_pca9846_channel_and_transfer] transfer data success
  [set_pca9846_channel_and_transfer] disable all channel and unlock, count: 0x0
  [set_pca9846_channel_and_transfer] device response data [0] [0]
  [ISR_SET_CHANNEL_1] success

4. Stress with 43090 times of mux sequential switch: Pass

2022-09-12 16:31 UTC, GoldenBug requested changes

2022-09-12 16:31 UTC, GoldenBug commented on common/dev/i2c-mux-pca984x.c
> +		LOG_ERR("[%s] transfer msg fail, status: %d\n", __func__, status);
Printing __func__ isn't necessary, it can be configured by the build systems and kconfig settings.
It can be removed from all the logging messages

2022-09-12 16:31 UTC, GoldenBug commented on common/dev/i2c-mux-pca984x.c
> +		LOG_ERR("[%s] transfer type is invalid, transfer type: %d\n", __func__, tran_type);
Printing __func__ isn't necessary, it can be configured by the build systems and kconfig settings.
It can be removed from all the logging messages

2022-09-12 16:31 UTC, GoldenBug commented
Printing __func__ isn't necessary, it can be configured by the build systems and kconfig settings.
It can be removed from all the logging messages

2022-09-13 00:39 UTC, LoraLin1 commented
Hi @GoldenBug,
Thanks for your comments.
Based on your suggestions to modify the code, and force update this branch.
Please help to review it again, thank you.

2022-09-14 06:22 UTC, closed without merging