Wc mb add source identify function and project command
facebook/OpenBIC pull request #574
Opened 2022-09-20 08:37 UTC by MouchenHung-QUANTA

Summary:
- Add source identification between main source and second source.
- Add project command.

Test Plan:
- Build Code: PASS
- Check project info command in BIC console:

Log:
- BIC console:
  ```
  uart:~$ wcmb info
  ========================{PLATFORM INFO}========================
  * NAME:          Waimea Canyon platform command
  * DESCRIPTION:   Commands that could be used to debug or validate.
  * Note:          none
  ------------------------------------------------------------------
  * SYSTEM CLASS:  Dual
  * SYSTEM SOURCE: Sencond
  ========================{PLATFORM INFO}========================
  ```

2022-09-21 20:35 UTC, GoldenBug requested changes

2022-09-21 20:35 UTC, GoldenBug commented on common/shell/commands/info_shell.c
>  #endif
We can use `CONFIG_BOARD` which is defined by Zephyr to get the board we're building for.
This means we don't have to define extra fields.

```
#ifndef CONFIG_BOARD
#define CONFIG_BOARD "unknown"
#endif
.
.
.
shell_print(shell, "* CHIP/OS:       %s - %s", CONFIG_BOARD, RTOS_TYPE);
```

2022-09-21 20:35 UTC, GoldenBug commented on meta-facebook/wc-mb/src/shell/commands/plat_info_shell.c
> +int cmd_wcmb_info_print(const struct shell *shell, size_t argc, char **argv)
I think we should make the `cmd_info_print (...)` __weak and just override it to include extra information.
I don't think it's necessary to make a different class of commands just for wc.

Instead we can add them to platform commands if we need to add new commands in the future.

2022-09-21 20:35 UTC, GoldenBug commented on meta-facebook/wc-mb/src/shell/commands/plat_info_shell.c
> +		    get_source_class() == SRC_MAIN ? "Main" : "Sencond");
Refactor the cmd_info_print function to something like this

```
void print_main_info(const struct shell *shell)
{
        shell_print(
                shell,
                "========================{SHELL COMMAND INFO}========================================");
        shell_print(shell, "* NAME:          Platform command");
        shell_print(shell, "* DESCRIPTION:   Commands that could be used to debug or validate.");
        shell_print(shell, "* DATE/VERSION:  none");
        shell_print(shell, "* CHIP/OS:       %s - %s", CONFIG_BOARD, RTOS_TYPE);
        shell_print(shell, "* Note:          none");
        shell_print(shell, "------------------------------------------------------------------");
        shell_print(shell, "* PLATFORM:      %s-%s", PLATFORM_NAME, PROJECT_NAME);
        shell_print(shell, "* BOARD ID:      %d", BOARD_ID);
        shell_print(shell, "* STAGE:         %d", PROJECT_STAGE);
        shell_print(shell, "* FW VERSION:    %d.%d", FIRMWARE_REVISION_1, FIRMWARE_REVISION_2);
        shell_print(shell, "* FW DATE:       %x%x.%x.%x", BIC_FW_YEAR_MSB, BIC_FW_YEAR_LSB,
                ⦙   BIC_FW_WEEK, BIC_FW_VER);
        shell_print(shell, "* FW IMAGE:      %s.bin", CONFIG_KERNEL_BIN_NAME);
        shell_print(
                shell,
                "========================{SHELL COMMAND INFO}========================================");
}

__weak int cmd_info_print(const struct shell *shell, size_t argc, char **argv)
{
        print_main_info(shell);
        return 0;
}
```

Then we can override this function and call the same print_main_info and then print the additional system_class info.

2022-09-21 20:35 UTC, GoldenBug commented on meta-facebook/wc-mb/src/shell/plat_shell.c
> +/*
no need to add a different type of command just for this system

2022-09-22 02:21 UTC, MouchenHung-QUANTA commented
Hi @GoldenBug ,

New commit has been uploaded, please have a look, thanks.

2022-09-23 19:23 UTC, closed without merging