common: shell: Add shell power commands
facebook/OpenBIC pull request #608
Opened 2022-09-30 07:33 UTC by MouchenHung-QUANTA

Summary:
- Add shell power commands
  - Get power status
    --> platform power status
  - Control power
    --> platform power control [device_name] [status]
    * **[device_name]**: host/bmc
    * **[status]**: on/off/reset

Test Plan:
- Build Code: PASS
- Check command results in BIC console: PASS

Log:
- BIC console:
  ```
  uart:~$ platform power status
  ------------------------------------
  [HOST]
  * status:      on
  * cpu status:  on
  * post status: on
  [BMC]
  * status: non-support
  ------------------------------------

  uart:~$ platform power control host off
  HOST power off successed!

  uart:~$ platform power status
  ------------------------------------
  [HOST]
  * status:      off
  * cpu status:  off
  * post status: off
  [BMC]
  * status: non-support
  ------------------------------------
  ```

2022-10-03 20:17 UTC, GoldenBug requested changes
A couple of minor change requests. Otherwise looks great!

2022-10-03 20:17 UTC, GoldenBug commented on common/shell/commands/power_shell.c
> +			shell_print(shell, "%s power %s successed!", device_info[DEVICE_HOST].name,
> succeeded

2022-10-03 20:17 UTC, GoldenBug commented on common/shell/commands/power_shell.c
> +		shell_warn(shell, "%s power control is not support", device_info[dev_idx].name);
> supported

2022-10-03 20:17 UTC, GoldenBug commented on common/shell/commands/power_shell.c
> +			shell_print(shell, "* status: non-support", device_info[i].name);
> not supported

2022-10-03 20:17 UTC, GoldenBug commented on common/shell/commands/power_shell.h
> +	MAX_DEVICE_CNT,
extend to `MAX_DEVICE_COUNT`

2022-10-04 03:01 UTC, MouchenHung-QUANTA commented
Hi @GoldenBug , new commit has been uploaded, please have a look, thanks!

2022-10-05 22:23 UTC, closed without merging