fby3: dl: Add Sensor HSC MP5990
facebook/OpenBIC pull request #639
Opened 2022-10-17 11:14 UTC by YoungLi123

Summary:
- Add Sensor HSC MP5990

Test plan:
- Build code: Pass
- Get HSC sensors and Outlet temp correctly

MP5990:
MB Outlet Temp               (0x2) :   37.00 C     | (ok)
HSC Temp                     (0xF) :   37.00 C     | (ok)
HSC Input Vol                (0x26) :   11.64 Volts | (ok)
HSC Output Cur               (0x30) :    2.40 Amps  | (ok)
HSC Input Pwr                (0x2E) :   28.00 Watts | (ok)
HSC Input AvgPwr             (0x39) :   28.00 Watts | (ok)

2022-10-17 21:22 UTC, GoldenBug requested changes

2022-10-17 21:22 UTC, GoldenBug commented on meta-facebook/yv3-dl/src/platform/plat_sensor_table.c
> +		printf("[%s] unsupported HSC module, HSC module: 0x%x\n", __func__, hsc_module);
LOG_ERR(...)
Remove newline.
Remove __func__ argument.

2022-10-17 21:22 UTC, GoldenBug commented on meta-facebook/yv3-dl/src/platform/plat_sensor_table.c
> +		printf("[%s] unsupported HSC module, HSC module: 0x%x\n", __func__, hsc_module);
LOG_ERR(...)
Remove newline.
Remove __func__ argument.

2022-10-17 21:22 UTC, GoldenBug commented on common/dev/mp5990.c
> +		LOG_WRN("i2c read failed.\n");
remove newline

2022-10-17 21:22 UTC, GoldenBug commented on common/dev/mp5990.c
> +		LOG_DBG("Energy difference is less than zero.\n");
remove newline

2022-10-17 21:22 UTC, GoldenBug commented on common/dev/mp5990.c
> +		LOG_DBG("Sample difference is less than zero.\n");
remove newline.

2022-10-18 01:43 UTC, YoungLi123 commented
Hi @GoldenBug 
Thanks for suggestions. I pushed a commit. Please review it again.

2022-10-19 06:25 UTC, closed without merging