at-cc: Support HSC and DC-to-DC power module device
facebook/OpenBIC pull request #650
Opened 2022-10-21 06:04 UTC by DelphineChiu

Summary:
- Support HSC (ADM1272) device.
- Support DC-to-DC power module (Q50SN120A1) device.

Test Plan:
- Build code: Pass

2022-10-24 20:12 UTC, GoldenBug requested changes

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +			LOG_ERR("convert value func: vrange 0x%x is invlid", vrange);
Remove function name
```
LOG_ERR("Vrange 0x%x is invlid", vrange);
```

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +			LOG_ERR("convert value func: irange 0x%x is invlid", irange);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +				LOG_ERR("convert value func: irange 0x%x is invlid", irange);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +				LOG_ERR("convert value func: irange 0x%x is invlid", irange);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +			LOG_ERR("convert value func: vrange 0x%x is invlid", vrange);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +		LOG_ERR("convert func: offset 0x%x is invalid", offset);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +		LOG_ERR("convert func: convert coefficient m is invalid, vrange: 0x%x, irange: 0x%x",
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +		LOG_ERR("read pout func: read Vout fail, ret: %d", ret);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/adm1272.c
> +		LOG_ERR("read pout func: read Iout fail, ret: %d", ret);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/q50sn120a1.c
> +		LOG_ERR("read func: not support offset: 0x%x", offset);
Remove function name at the beginning of the log.

2022-10-24 20:12 UTC, GoldenBug commented on common/dev/q50sn120a1.c
> +		LOG_ERR("init func: input sensor number is invalid");
Remove function name at the beginning of the log.

2022-10-25 02:24 UTC, LoraLin1 commented
Hi @GoldenBug ,
Thanks for your comments.
Based on your suggestions to modify the code, rebase main and force update this branch.
Please help to review it again, thank you.

2022-10-27 20:33 UTC, closed without merging