fby3.5: hd: Record BIOS firmware version in EEPROM
facebook/OpenBIC pull request #698
Opened 2022-11-18 08:34 UTC by Yi-Shum

Summary:
- Record BIOS firmware version in EEPROM.
- Support ipmi oem command (netfn = 0x38, cmd = 0xA2) to support BMC get BIOS firmware version.

Test Plan:
- Build code: Pass

2022-11-28 17:55 UTC, GoldenBug requested changes

2022-11-28 17:55 UTC, GoldenBug commented on meta-facebook/yv35-hd/src/ipmi/plat_ipmi.c
> +	msg->data_len = 0;
This must be true, so isn't needed here because of line 114

2022-11-28 17:55 UTC, GoldenBug commented on meta-facebook/yv35-hd/src/ipmi/plat_ipmi.c
> +	if (ret == -1) {
`(ret < 0)`

In case new errors are returned in the future.

2022-11-29 19:02 UTC, GoldenBug approved these changes

2022-11-30 01:12 UTC, Yi-Shum commented
Hi @GoldenBug, thanks for your comments.
I add a commit for it, please help review it again.

2022-12-02 06:23 UTC, closed without merging