common: Add pldm update function for 3 types of vr
facebook/OpenBIC pull request #780
Opened 2022-12-27 08:45 UTC by MouchenHung-QUANTA

Summary:
- Add pldm update code for three vr devices isl69259, mp2971, xdpe12284c.

Test Plan:
- Build Code: PASS

2023-01-04 22:09 UTC, garnermic requested changes

2023-01-04 22:09 UTC, garnermic commented on common/dev/xdpe12284c.c
> +		if (rec_flag == true) {
Is there a way to simplify this set of if statements.  Going 5 levels deep is too many to follow and maintain easily.

2023-01-04 22:09 UTC, garnermic commented on common/dev/xdpe12284c.c
> +		if (i + 9 < fw_update_cfg.image_size) {
This needs to be refactored as 7 level deep if statements are not easily maintained.

2023-01-04 22:09 UTC, garnermic commented on common/dev/xdpe12284c.c
> +	}
This needs an else statement to catch any other conditions.

2023-01-04 22:09 UTC, garnermic commented on common/dev/xdpe12284c.c
> +	uint8_t remain = 0;
Since some of the VRs have up to 1000 rewrites, should this still be a uint8_t?

2023-01-04 22:09 UTC, garnermic commented on common/dev/xdpe12284c.c
> +	} while (0);
Why the need for a do while if it is only going to be a single pass?

2023-01-04 22:09 UTC, garnermic commented on common/dev/xdpe12284c.c
> +	// TODO
Will this be in a future commit?

2023-01-09 06:25 UTC, MouchenHung-QUANTA commented
Hi @garnermic , please have a look at two updated commits, which have followed given suggestions, thanks!

2023-01-11 21:23 UTC, closed without merging