GT: Add platform-related alert pin PLDM event log
facebook/OpenBIC pull request #796
Opened 2023-01-09 09:06 UTC by Quanta-YangChen

Summary:
- Change the behavior to load the sensor table by different sources.
- Modify the stage naming way of the GT stage to avoid naming conflicts to the common.
- Add SSD ADC alert pin check and send by different power monitor IC.

Test Plan:
- Build code: Pass

2023-01-09 16:27 UTC, garnermic commented on common/service/pldm/pldm_monitor.c
>  {
Please test work for NULL.

2023-01-09 16:27 UTC, garnermic commented on meta-facebook/gt-cc/src/platform/plat_pldm_monitor.c
> +void ssd_alert_check_ina230(uint8_t idx, uint8_t *flag)
Please test flag for NULL.

2023-01-09 16:27 UTC, garnermic commented on meta-facebook/gt-cc/src/platform/plat_pldm_monitor.c
> +	sensor_cfg *cfg = &sensor_config[sensor_config_index_map[sensor_num]];
Please test cfg for NULL before using.

2023-01-09 16:27 UTC, garnermic commented on meta-facebook/gt-cc/src/platform/plat_pldm_monitor.c
> +
Please check flag and cfg for NULL before referencing.

2023-01-09 16:27 UTC, garnermic commented on meta-facebook/gt-cc/src/platform/plat_pldm_monitor.c
> +	struct ssd_event_check *data = CONTAINER_OF(work, struct ssd_event_check, work);
Please test work and data for NULL before using.

2023-01-09 16:27 UTC, garnermic commented on meta-facebook/gt-cc/src/platform/plat_pldm_monitor.c
> +	if (!data->init) {
Please test data for NULL before using.

2023-01-09 16:28 UTC, garnermic requested changes
Please resolve the 6 issues as mentioned in my review comments.

2023-01-10 04:30 UTC, Quanta-YangChen commented
Hi @garnermic ,

Already update a [commit](https://github.com/facebook/OpenBIC/pull/798/commits/c23ed4e60b500713d5e8cc60f36168fa1ff736cf) modification as suggested. Please review it again, thank you.

2023-01-12 20:46 UTC, garnermic commented
Please resolve issues in the commit they are reported as it makes it difficult to verify the fixes and to ensure everything builds correctly in case the follow-on commit doesn't get merged before a build is needed.

2023-01-16 12:39 UTC, Quanta-YangChen commented
Hi @garnermic , 

PR #795, #796, #797, and #798 have been successfully built pass on all platforms, please help review them again. Thank you.

2023-01-18 13:51 UTC, Quanta-YangChen commented
Close this PR, and will resolve all checks in later PR.

2023-01-18 13:51 UTC, closed without merging