common - Add pldm cpld update and improve pldm update common code
facebook/OpenBIC pull request #799
Opened 2023-01-09 09:45 UTC by MouchenHung-QUANTA

Summary:
- Support cpld pldm fw update
- Support vr update for Grand Teton

Test Plan:
- Build Code: PASS

2023-01-09 09:48 UTC, MouchenHung-QUANTA commented
Hi @garnermic , This pull request is based on #780 , thanks!

2023-01-09 17:21 UTC, garnermic requested changes

2023-01-09 17:21 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +	memcpy(hex_buff + p->data_ofs, p->data, p->data_len);
if p->data_ofs is not zero, then hex_buff is NULL here.

2023-01-10 02:24 UTC, MouchenHung-QUANTA commented
Hi @garnermic , New commit has fix the problem, thanks for remind.

2023-01-12 01:52 UTC, garnermic requested changes
Request was made to have the Github actions addressed before Meta approval.

2023-01-12 02:42 UTC, garnermic commented
The latest update still shows it is failing Github checks as shown below.

Build and Analyze / run-cppcheck
Build and Analyze / run-clang-format
Build and Analyze / Aggregate-Lint-Output

2023-01-12 02:59 UTC, MouchenHung-QUANTA commented
Hi @garnermic , merge conflict problem has been solved, please have a look, thanks!

2023-01-13 02:56 UTC, MouchenHung-QUANTA commented
Since #800 has been merged, so closed this pull request.

2023-01-13 02:56 UTC, closed without merging