common: Support pldm update commands GetStatus and CancelUpdate
facebook/OpenBIC pull request #823
Opened 2023-01-16 11:20 UTC by MouchenHung-QUANTA

Summary:
- Support pldm update command GetStatus(0x1B) and CancelUpdate(0x1D).
- Fix state machine.

Test Plan:
- Build Code: PASS

2023-01-17 16:40 UTC, garnermic requested changes

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +		LOG_ERR("First package(offset=0) has missed, so hex_buff get NULL");
Can you clean up this error message.  Is it indicating the offset for the first package had some missing?  The if statement already is clear that hex_buff is NULL at this point so no need to put that in the error message.

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +			LOG_WRN("Update has been canceled by UA");
Can you spell out UA as the acronym isn't obvious.

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +		LOG_ERR("Current mode %d doesn't meet request state %d", current_state, STATE_IDLE);
Can we improve this error message?  I think the message should be something like "firmware update failed because current state is not idle"

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +		LOG_ERR("Current mode %d doesn't meet request state %d", current_state,
Similar to above, this should indicate something like "firmware update failed because current state %d is invalid", current_state

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +		LOG_ERR("Current mode %d doesn't meet request state %d", current_state,
Please update message to be more clear...something like "firmware update failed because current state %d is not in update mode"

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +		LOG_ERR("Current mode %d doesn't meet request state %d", current_state,
Please update error message to be more accurate.

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +	if (!mctp_inst || !buf || !resp || !resp_len || !ext_params) {
Please use CHECK_NULL_ARG_WITH_RETURN for each argument.

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +	if (!mctp_inst || !buf || !resp || !resp_len || !ext_params) {
Please use CHECK_NULL_ARG_WITH_RETURN for each argument.

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +		LOG_ERR("Current mode already in IDLE state");
Please provide more accurate error message.

2023-01-17 16:40 UTC, garnermic commented on common/service/pldm/pldm_firmware_update.c
> +	LOG_INF("Cancel update");
Update canceled

2023-01-18 02:26 UTC, MouchenHung-QUANTA commented
Hi @garnermic , new commit has been pushed, please have a look, thanks!

2023-01-25 23:23 UTC, closed without merging