fby35: gl: Configure GPIO interrupt function
facebook/OpenBIC pull request #884
Opened 2023-02-07 07:14 UTC by BonnieLo

Summary:
- BIC accesses the interrupt function when specific GPIOs rising/falling.

Test Plan:
Enable "IRQ_SML1_PMBUS_ALERT_N" and "FM_DBP_PRESENT_N" to check if BIC accesses interrupt function successfully.

Test Log:
    uart:~$ platform gpio list_all IRQ_SML1_PMBUS_ALERT_N
    [41 ] IRQ_SML1_PMBUS_ALERT_N             : OD  | input (O) | 0(0)
    uart:~$ platform gpio set val 41 1
    access IRQ_SML1_PMBUS_ALERT_N (Add debug message to check if BIC accesses interrupt function)
    gpio[41] --> 1 ,success!
    uart:~$ platform gpio list_all IRQ_SML1_PMBUS_ALERT_N
    [41 ] IRQ_SML1_PMBUS_ALERT_N             : OD  | input (I) | 1(1)

    uart:~$ platform gpio list_all FM_DBP_PRESENT_N
    [44 ] FM_DBP_PRESENT_N                   : OD  | input (O) | 0(0)
    uart:~$ platform gpio set val 44 1
    access FM_DBP_PRESENT_N (Add debug message to check if BIC accesses interrupt function)
    gpio[44] --> 1 ,success!
    uart:~$ platform gpio list_all FM_DBP_PRESENT_N
    [44 ] FM_DBP_PRESENT_N                   : OD  | input (I) | 1(1)

2023-02-07 14:42 UTC, garnermic requested changes

2023-02-07 14:42 UTC, garnermic commented on meta-facebook/yv35-gl/src/platform/plat_isr.c
> + * TODO :
Please remove todo comments.

2023-02-07 14:42 UTC, garnermic commented on meta-facebook/yv35-gl/src/platform/plat_isr.c
> +		/*
Please remove todo comments.

2023-02-08 01:05 UTC, JeffShih-wiwynn commented on meta-facebook/yv35-gl/src/platform/plat_isr.c
> + * TODO :
Todo comments are removed. Please check, thanks.

2023-02-08 01:05 UTC, JeffShih-wiwynn commented on meta-facebook/yv35-gl/src/platform/plat_isr.c
> +		/*
Todo comments are removed. Please check, thanks.

2023-02-08 01:32 UTC, garnermic commented
This PR conflicts with #880. Can you rebase the two and re-submit this PR?

2023-02-08 19:24 UTC, closed without merging