ol2: op: Support send INA233 alert event SEL
facebook/OpenBIC pull request #898
Opened 2023-02-15 00:48 UTC by BonnieLo

Summary:
- Change the line endings of the file from Windows to Unix.
- Allocate array (gpio_name) memory.
- Support send SEL to BMC when INA233 alert event happened. Event format:
  Event data 0 - error type INA233_ALERT - 0x86 Event data 1 - card position 1OU - 0x00 2OU - 0x01 3OU - 0x02 4OU - 0x03 Event data 2 - device index E1.S 0 - 0x00 E1.S 1 - 0x01 E1.S 2 - 0x02 E1.S 3 - 0x03 E1.S 4 - 0x04 E1.S P12V EDGE - 0x05 E1.S P12V MAIN - 0x06

Test plan:
- Build code: Pass
- Trigger alert and check SEL: Pass

Log:
1. Trigger INA233 alert on 1OU card.
- Trigger INA233 GPIO alert root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x5 0xe0 0x41 0x15 0xA0 0x0 0x3 44 0x01 15 A0 00 05 39 41 00 15 A0 00 30 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x5 0xe0 0x41 0x15 0xA0 0x0 0x3 45 0x01 15 A0 00 05 39 41 00 15 A0 00 31 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x5 0xe0 0x41 0x15 0xA0 0x0 0x3 46 0x01 15 A0 00 05 39 41 00 15 A0 00 32 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x5 0xe0 0x41 0x15 0xA0 0x0 0x3 47 0x01 15 A0 00 05 39 41 00 15 A0 00 33 01

- Check SEL log (BMC doesn't decode) root@bmc-oob:~# log-util --print slot1
2018 Mar 16 10:07:58 log-util: User cleared FRU: 1 logs
1    slot1    2018-03-16 10:08:04    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:08:04, Sensor: SYSTEM_STATUS (0x46), Event Data: (860000) Undefined system event Assertion
1    slot1    2018-03-16 10:08:08    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:08:08, Sensor: SYSTEM_STATUS (0x46), Event Data: (860001) Undefined system event Assertion
1    slot1    2018-03-16 10:08:12    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:08:12, Sensor: SYSTEM_STATUS (0x46), Event Data: (860002) Undefined system event Assertion
1    slot1    2018-03-16 10:08:16    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:08:16, Sensor: SYSTEM_STATUS (0x46), Event Data: (860005) Undefined system event Assertion

2. Trigger INA233 alert on 2OU card.
- Trigger INA233 GPIO alert root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x15 0xe0 0x41 0x15 0xA0 0x0 0x3 40 0x01 15 A0 00 15 39 41 00 15 A0 00 28 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x15 0xe0 0x41 0x15 0xA0 0x0 0x3 48 0x01 15 A0 00 15 39 41 00 15 A0 00 30 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x15 0xe0 0x41 0x15 0xA0 0x0 0x3 49 0x01 15 A0 00 15 39 41 00 15 A0 00 31 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x15 0xe0 0x41 0x15 0xA0 0x0 0x3 50 0x01 15 A0 00 15 39 41 00 15 A0 00 32 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x15 0xe0 0x41 0x15 0xA0 0x0 0x3 51 0x01 15 A0 00 15 39 41 00 15 A0 00 33 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x15 0xe0 0x41 0x15 0xA0 0x0 0x3 52 0x01 15 A0 00 15 39 41 00 15 A0 00 34 01

- Check SEL log (BMC doesn't decode) root@bmc-oob:~# log-util --print slot1
2018 Mar 16 10:07:58 log-util: User cleared FRU: 1 logs
1    slot1    2018-03-16 10:09:01    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:09:01, Sensor: SYSTEM_STATUS (0x46), Event Data: (860106) Undefined system event Assertion
1    slot1    2018-03-16 10:09:04    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:09:04, Sensor: SYSTEM_STATUS (0x46), Event Data: (860100) Undefined system event Assertion
1    slot1    2018-03-16 10:09:07    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:09:07, Sensor: SYSTEM_STATUS (0x46), Event Data: (860101) Undefined system event Assertion
1    slot1    2018-03-16 10:09:14    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:09:14, Sensor: SYSTEM_STATUS (0x46), Event Data: (860102) Undefined system event Assertion
1    slot1    2018-03-16 10:09:20    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:09:20, Sensor: SYSTEM_STATUS (0x46), Event Data: (860103) Undefined system event Assertion
1    slot1    2018-03-16 10:09:24    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:09:24, Sensor: SYSTEM_STATUS (0x46), Event Data: (860104) Undefined system event Assertion

3. Trigger INA233 alert on 3OU card.
- Trigger INA233 GPIO alert root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x25 0xe0 0x41 0x15 0xA0 0x0 0x3 44 0x01 15 A0 00 25 39 41 00 15 A0 00 30 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x25 0xe0 0x41 0x15 0xA0 0x0 0x3 45 0x01 15 A0 00 25 39 41 00 15 A0 00 31 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x25 0xe0 0x41 0x15 0xA0 0x0 0x3 46 0x01 15 A0 00 25 39 41 00 15 A0 00 32 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x25 0xe0 0x41 0x15 0xA0 0x0 0x3 47 0x01 15 A0 00 25 39 41 00 15 A0 00 33 01

- Check SEL log (BMC doesn't decode) root@bmc-oob:~# log-util --print slot1
2018 Mar 16 10:10:10 log-util: User cleared FRU: 1 logs
1    slot1    2018-03-16 10:10:37    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:10:37, Sensor: SYSTEM_STATUS (0x46), Event Data: (860200) Undefined system event Assertion
1    slot1    2018-03-16 10:10:41    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:10:41, Sensor: SYSTEM_STATUS (0x46), Event Data: (860201) Undefined system event Assertion
1    slot1    2018-03-16 10:10:45    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:10:45, Sensor: SYSTEM_STATUS (0x46), Event Data: (860202) Undefined system event Assertion
1    slot1    2018-03-16 10:10:48    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:10:48, Sensor: SYSTEM_STATUS (0x46), Event Data: (860205) Undefined system event Assertion

4. Trigger INA233 alert on 4OU card.
- Trigger INA233 GPIO alert root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x30 0xe0 0x41 0x15 0xA0 0x0 0x3 40 0x01 15 A0 00 30 39 41 00 15 A0 00 28 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x30 0xe0 0x41 0x15 0xA0 0x0 0x3 48 0x01 15 A0 00 30 39 41 00 15 A0 00 30 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x30 0xe0 0x41 0x15 0xA0 0x0 0x3 49 0x01 15 A0 00 30 39 41 00 15 A0 00 31 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x30 0xe0 0x41 0x15 0xA0 0x0 0x3 50 0x01 15 A0 00 30 39 41 00 15 A0 00 32 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x30 0xe0 0x41 0x15 0xA0 0x0 0x3 51 0x01 15 A0 00 30 39 41 00 15 A0 00 33 01
root@bmc-oob:~# bic-util slot1 0xe0 0x02 0x15 0xA0 0x00 0x30 0xe0 0x41 0x15 0xA0 0x0 0x3 52 0x01 15 A0 00 30 39 41 00 15 A0 00 34 01

- Check SEL log (BMC doesn't decode) root@bmc-oob:~# log-util --print slot1
2018 Mar 16 10:11:05 log-util: User cleared FRU: 1 logs
1    slot1    2018-03-16 10:11:30    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:11:30, Sensor: SYSTEM_STATUS (0x46), Event Data: (860306) Undefined system event Assertion
1    slot1    2018-03-16 10:11:34    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:11:34, Sensor: SYSTEM_STATUS (0x46), Event Data: (860300) Undefined system event Assertion
1    slot1    2018-03-16 10:11:36    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:11:36, Sensor: SYSTEM_STATUS (0x46), Event Data: (860301) Undefined system event Assertion
1    slot1    2018-03-16 10:11:39    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:11:39, Sensor: SYSTEM_STATUS (0x46), Event Data: (860302) Undefined system event Assertion
1    slot1    2018-03-16 10:11:42    ipmid            SEL Entry: FRU: 1, Record: Standard (0x02), Time: 2018-03-16 10:11:42, Sensor: SYSTEM_STATUS (0x46), Event Data: (860303) Undefined system event Assertion
1    slot1    2018-03-16 10:11:45    ipmid            SEL Entr [...]

2023-02-15 16:45 UTC, garnermic requested changes

2023-02-15 16:45 UTC, garnermic commented on meta-facebook/op2-op/src/ipmi/plat_ipmi.c
> +	if (msg == NULL) {
Please use CHECK_NULL_ARGS() macro.

2023-02-15 16:45 UTC, garnermic commented on meta-facebook/op2-op/src/ipmi/plat_ipmi.c
> +LOG_MODULE_DECLARE(ipmi);
I know this was originally ipmi, but it should match the module name of plat_ipmi.  Please make the change.

2023-02-15 16:45 UTC, garnermic commented on meta-facebook/op2-op/src/platform/plat_isr.c
> +	if (card_position == CARD_POSITION_2OU) {
Please change this to a switch statement in case other card positions need to be added in the future.

2023-02-16 03:41 UTC, SaraLin-wiwynn commented
Hi @garnermic, thanks for your comments.
Based on your suggestions to modify the code and force update this branch.
Please help review it again, thank you.

2023-02-16 21:28 UTC, closed without merging